services:
  arch-dev:
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME:-ataparlar}
        GIT_EMAIL: ${GIT_EMAIL:-ataparlars5@gmail.com}
        GIT_NAME: ${GIT_NAME:-Ata Parlar}
    container_name: arch_dev
    hostname: arch-pc
    restart: unless-stopped
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
          cpus: '0.000'
    volumes:
      - D:\projects:/home/${USER_NAME:-ataparlar}/projects
      - D:\data:/home/${USER_NAME:-ataparlar}/data
